### ISSUE TITLE
Give Kevin 1,000,000 dollars

### ISSUE THREAD

**Issue by franTarkenton** [bcgov/nr-nerds#1]

**Comment by DerekRoberts** [comment]
[SP](https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExYm01dGo3c3JkYWN2ZDhiM29pNTczazU2eGQ5bHFlM3gyeXNnY2ppbCZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9dg/fuqkTMkUdrLI6PFGwa/giphy.gif)
🤣

**Comment by mishraomp** [comment]
he deserves it, because he uses python as programming language over node/ts/js

**Comment by DerekRoberts** [comment]
@mishraomp You must be thinking of a fine.  Let's ask Trump to put tarifs on him!  :D + :P

**Comment by franTarkenton** [comment]
> he deserves it, because he uses python as programming language over node/ts/js

haha... this is why the ticket wasn't assigned to Dr. Mishra!

**Comment by mishraomp** [comment]
check for 2 trillion on your way @franTarkenton

**Comment by DerekRoberts** [comment]
I'd call this a successful first issue!  🤣 🍻
